name: Simple CI

on:
  push:
    branches:
      - master

  pull_request:
    branchs:
      - master

jobs:
  simple_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: npm install
        run: npm install

      - name: eslint
        run: npm run eslint

      - name: build
        run: npm run build

      - name: test
        run: npm run test:nowatch
